DROP TABLE USERS IF EXISTS;
DROP TABLE ADVICES IF EXISTS;

CREATE TABLE USERS(
-- 	ID VARCHAR(25) PRIMARY KEY,
	NAME VARCHAR(50),
	PASSWORD VARCHAR(50)
);

CREATE TABLE ADVICES(
-- 	ID VARCHAR(25) PRIMARY KEY,
	ROAST VARCHAR(50),
	ADVICE VARCHAR(250)
);

