INSERT INTO USERS VALUES('Dave', '111');
INSERT INTO USERS VALUES('Steve', '222');
INSERT INTO USERS VALUES('Ralph', '333');

INSERT INTO ADVICES VALUES('dark', 'Sumatra');
INSERT INTO ADVICES VALUES('dark', 'Verona');
INSERT INTO ADVICES VALUES('dark', 'French Roast');
INSERT INTO ADVICES VALUES('medium', 'Breakfast Blend');
INSERT INTO ADVICES VALUES('medium', 'Colombia');
INSERT INTO ADVICES VALUES('medium', 'Yukon');
INSERT INTO ADVICES VALUES('medium', 'Pike Place');
INSERT INTO ADVICES VALUES('medium', 'House Blend');
INSERT INTO ADVICES VALUES('light', 'Willow');
INSERT INTO ADVICES VALUES('light', 'Aria');
INSERT INTO ADVICES VALUES('light', 'Bright Sky');
INSERT INTO ADVICES VALUES('light', 'Veranda');
